name: IGPSport Data Sync To Xingzhe 

on:
  workflow_dispatch: 
  schedule:
    - cron: '32 7/8 * * *' #07:30, 15:32, 23:32
  watch:
    types: started

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run srcipt
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |
        python ActivitySync.py
